version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - pip install -r requirements.txt
      - pip install git+https://github.com/paminov/django-warrant.git
      - python manage.py makemigrations easystore
      - python manage.py migrate

  pre_build:
    commands:
      - python manage.py test
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
