# Generated by Django 2.1.2 on 2018-10-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(db_index=True, max_length=36)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
